import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblDad: String = "Dad"
    static let kLblMyTherapist: String = "My therapist"
    static let kLblSendTheSOS: String = "Send the S.O.S"
    static let kLblHome: String = "Home"
    static let kMsgYourPhoneNumb: String = "Your phone number (Required)"
    static let kMsg656333444: String = "(656) - 333 4444"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblReportAPerson: String = "Report a person"
    static let kMsgWhatActionDo: String = "What action do you want to take?"
    static let kMsg656111222: String = "(656) - 111 2222"
    static let kLblSis: String = "Sis"
    static let kLblSosSent: String = "SOS sent"
    static let kLblSafeparty: String = "SafeParty"
    static let kLblSosMode: String = "SOS mode"
    static let kMsgYourReportHas: String = "Your report has been sent to USFPD."
    static let kLblPanicMode: String = "PANIC mode"
    static let kMsgYourEmailReq: String = "Your email (Required)"
    static let kLblBestie: String = "Bestie"
    static let kLblReport: String = "Report"
    static let kLblProfile: String = "Profile"
    static let kMsgWeProtectYou: String = "We protect you together."
    static let kMsg959555666: String = "(959) - 555 6666"
    static let kMsgYourNameRequ: String = "Your name (Required)"
    static let kLblLogInAsHost: String = "Log in as Host"
    static let kLblReportSent: String = "Report sent"
    static let kLblReportToHost: String = "Report to Host"
    static let kMsgLogInAsAtten: String = "Log in as Attendee"
    static let kLblMyEvents: String = "My events"
    static let kMsgPerpetratorSN: String = "Perpetrator’s name (Required)"
    static let kMsg757888999: String = "(757) - 888 9999"
    static let kMsgYourReportHas2: String = "Your report has been sent to Host."
    static let kLblRoommate: String = "Roommate"
    static let kLblSOSMode2: String = "S.O.S Mode"
    static let kMsgDescriptionRe: String = "Description (Required)"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgYouAreNotAlo: String = "You are not alone. Let us help you out."
    static let kMsgClickHereToA: String = "Click here to attach photos"
    static let kMsgIncludePreviou: String = "Include previous PANIC information."
    static let kLblReturnToMenu: String = "Return to menu"
    static let kMsg513777666: String = "(513) - 777 6666"
    static let kMsgEmergencyConta: String = "Emergency contacts"
    static let kLblReportToUsfpd: String = "Report to USFPD"
    static let kMsg985000333: String = "(985) - 000 3333 "
    static let kMsgYourSosHasBe: String = "Your SOS has been sent to your emergency contacts."
    static let kLblPartyAttended: String = "Party attended:"
    static let kLblMom: String = "Mom"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgWeWillSendA: String =
        "We will send a SMS message, along with your current location and party you are attending, to 6 emeregency contacts on your phone."
}
